/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.account.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AccountRoleEntry service. Represents a row in the &quot;DG_AccountRoleEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.dogoo.account.model.impl.AccountRoleEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.dogoo.account.model.impl.AccountRoleEntryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountRoleEntry
 * @generated
 */
@ProviderType
public interface AccountRoleEntryModel
	extends BaseModel<AccountRoleEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account role entry model instance should use the {@link AccountRoleEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this account role entry.
	 *
	 * @return the primary key of this account role entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this account role entry.
	 *
	 * @param primaryKey the primary key of this account role entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this account role entry.
	 *
	 * @return the uuid of this account role entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this account role entry.
	 *
	 * @param uuid the uuid of this account role entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the account role ID of this account role entry.
	 *
	 * @return the account role ID of this account role entry
	 */
	public long getAccountRoleId();

	/**
	 * Sets the account role ID of this account role entry.
	 *
	 * @param AccountRoleId the account role ID of this account role entry
	 */
	public void setAccountRoleId(long AccountRoleId);

	/**
	 * Returns the group ID of this account role entry.
	 *
	 * @return the group ID of this account role entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this account role entry.
	 *
	 * @param groupId the group ID of this account role entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this account role entry.
	 *
	 * @return the company ID of this account role entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this account role entry.
	 *
	 * @param companyId the company ID of this account role entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this account role entry.
	 *
	 * @return the user ID of this account role entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this account role entry.
	 *
	 * @param userId the user ID of this account role entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this account role entry.
	 *
	 * @return the user uuid of this account role entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this account role entry.
	 *
	 * @param userUuid the user uuid of this account role entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this account role entry.
	 *
	 * @return the user name of this account role entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this account role entry.
	 *
	 * @param userName the user name of this account role entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this account role entry.
	 *
	 * @return the create date of this account role entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this account role entry.
	 *
	 * @param createDate the create date of this account role entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this account role entry.
	 *
	 * @return the modified date of this account role entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this account role entry.
	 *
	 * @param modifiedDate the modified date of this account role entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the account ID of this account role entry.
	 *
	 * @return the account ID of this account role entry
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this account role entry.
	 *
	 * @param AccountId the account ID of this account role entry
	 */
	public void setAccountId(long AccountId);

	/**
	 * Returns the name of this account role entry.
	 *
	 * @return the name of this account role entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this account role entry.
	 *
	 * @param name the name of this account role entry
	 */
	public void setName(String name);

	/**
	 * Returns the code of this account role entry.
	 *
	 * @return the code of this account role entry
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this account role entry.
	 *
	 * @param code the code of this account role entry
	 */
	public void setCode(String code);

}