/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.poc.pet.model.impl;

import com.dogoo.poc.pet.model.CatEntry;
import com.dogoo.poc.pet.model.CatEntryModel;
import com.dogoo.poc.pet.model.CatEntrySoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the CatEntry service. Represents a row in the &quot;DG_CatEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>CatEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CatEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CatEntryImpl
 * @generated
 */
@JSON(strict = true)
public class CatEntryModelImpl
	extends BaseModelImpl<CatEntry> implements CatEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a cat entry model instance should use the <code>CatEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "DG_CatEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"petId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"creatorId", Types.BIGINT}, {"scopeOrgId", Types.BIGINT},
		{"name", Types.VARCHAR}, {"tag", Types.VARCHAR},
		{"status", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("petId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("creatorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("scopeOrgId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("tag", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table DG_CatEntry (uuid_ VARCHAR(75) null,petId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,creatorId LONG,scopeOrgId LONG,name VARCHAR(75) null,tag VARCHAR(75) null,status VARCHAR(75) null,statusDate DATE null)";

	public static final String TABLE_SQL_DROP = "drop table DG_CatEntry";

	public static final String ORDER_BY_JPQL = " ORDER BY catEntry.name ASC";

	public static final String ORDER_BY_SQL = " ORDER BY DG_CatEntry.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TAG_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static CatEntry toModel(CatEntrySoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CatEntry model = new CatEntryImpl();

		model.setUuid(soapModel.getUuid());
		model.setPetId(soapModel.getPetId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setCreatorId(soapModel.getCreatorId());
		model.setScopeOrgId(soapModel.getScopeOrgId());
		model.setName(soapModel.getName());
		model.setTag(soapModel.getTag());
		model.setStatus(soapModel.getStatus());
		model.setStatusDate(soapModel.getStatusDate());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<CatEntry> toModels(CatEntrySoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CatEntry> models = new ArrayList<CatEntry>(soapModels.length);

		for (CatEntrySoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public CatEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _petId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _petId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CatEntry.class;
	}

	@Override
	public String getModelClassName() {
		return CatEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<CatEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<CatEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CatEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((CatEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<CatEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<CatEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(CatEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<CatEntry, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<CatEntry, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, CatEntry>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			CatEntry.class.getClassLoader(), CatEntry.class,
			ModelWrapper.class);

		try {
			Constructor<CatEntry> constructor =
				(Constructor<CatEntry>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<CatEntry, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<CatEntry, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<CatEntry, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<CatEntry, Object>>();
		Map<String, BiConsumer<CatEntry, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<CatEntry, ?>>();

		attributeGetterFunctions.put("uuid", CatEntry::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<CatEntry, String>)CatEntry::setUuid);
		attributeGetterFunctions.put("petId", CatEntry::getPetId);
		attributeSetterBiConsumers.put(
			"petId", (BiConsumer<CatEntry, Long>)CatEntry::setPetId);
		attributeGetterFunctions.put("groupId", CatEntry::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<CatEntry, Long>)CatEntry::setGroupId);
		attributeGetterFunctions.put("companyId", CatEntry::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<CatEntry, Long>)CatEntry::setCompanyId);
		attributeGetterFunctions.put("userId", CatEntry::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<CatEntry, Long>)CatEntry::setUserId);
		attributeGetterFunctions.put("userName", CatEntry::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<CatEntry, String>)CatEntry::setUserName);
		attributeGetterFunctions.put("createDate", CatEntry::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<CatEntry, Date>)CatEntry::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", CatEntry::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<CatEntry, Date>)CatEntry::setModifiedDate);
		attributeGetterFunctions.put("creatorId", CatEntry::getCreatorId);
		attributeSetterBiConsumers.put(
			"creatorId", (BiConsumer<CatEntry, Long>)CatEntry::setCreatorId);
		attributeGetterFunctions.put("scopeOrgId", CatEntry::getScopeOrgId);
		attributeSetterBiConsumers.put(
			"scopeOrgId", (BiConsumer<CatEntry, Long>)CatEntry::setScopeOrgId);
		attributeGetterFunctions.put("name", CatEntry::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<CatEntry, String>)CatEntry::setName);
		attributeGetterFunctions.put("tag", CatEntry::getTag);
		attributeSetterBiConsumers.put(
			"tag", (BiConsumer<CatEntry, String>)CatEntry::setTag);
		attributeGetterFunctions.put("status", CatEntry::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<CatEntry, String>)CatEntry::setStatus);
		attributeGetterFunctions.put("statusDate", CatEntry::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate", (BiConsumer<CatEntry, Date>)CatEntry::setStatusDate);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getPetId() {
		return _petId;
	}

	@Override
	public void setPetId(long petId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_petId = petId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public long getCreatorId() {
		return _creatorId;
	}

	@Override
	public void setCreatorId(long creatorId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_creatorId = creatorId;
	}

	@JSON
	@Override
	public long getScopeOrgId() {
		return _scopeOrgId;
	}

	@Override
	public void setScopeOrgId(long scopeOrgId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_scopeOrgId = scopeOrgId;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	@JSON
	@Override
	public String getTag() {
		if (_tag == null) {
			return "";
		}
		else {
			return _tag;
		}
	}

	@Override
	public void setTag(String tag) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tag = tag;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalTag() {
		return getColumnOriginalValue("tag");
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return "";
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_statusDate = statusDate;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(CatEntry.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), CatEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CatEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, CatEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CatEntryImpl catEntryImpl = new CatEntryImpl();

		catEntryImpl.setUuid(getUuid());
		catEntryImpl.setPetId(getPetId());
		catEntryImpl.setGroupId(getGroupId());
		catEntryImpl.setCompanyId(getCompanyId());
		catEntryImpl.setUserId(getUserId());
		catEntryImpl.setUserName(getUserName());
		catEntryImpl.setCreateDate(getCreateDate());
		catEntryImpl.setModifiedDate(getModifiedDate());
		catEntryImpl.setCreatorId(getCreatorId());
		catEntryImpl.setScopeOrgId(getScopeOrgId());
		catEntryImpl.setName(getName());
		catEntryImpl.setTag(getTag());
		catEntryImpl.setStatus(getStatus());
		catEntryImpl.setStatusDate(getStatusDate());

		catEntryImpl.resetOriginalValues();

		return catEntryImpl;
	}

	@Override
	public int compareTo(CatEntry catEntry) {
		int value = 0;

		value = getName().compareTo(catEntry.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof CatEntry)) {
			return false;
		}

		CatEntry catEntry = (CatEntry)object;

		long primaryKey = catEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<CatEntry> toCacheModel() {
		CatEntryCacheModel catEntryCacheModel = new CatEntryCacheModel();

		catEntryCacheModel.uuid = getUuid();

		String uuid = catEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			catEntryCacheModel.uuid = null;
		}

		catEntryCacheModel.petId = getPetId();

		catEntryCacheModel.groupId = getGroupId();

		catEntryCacheModel.companyId = getCompanyId();

		catEntryCacheModel.userId = getUserId();

		catEntryCacheModel.userName = getUserName();

		String userName = catEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			catEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			catEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			catEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			catEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			catEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		catEntryCacheModel.creatorId = getCreatorId();

		catEntryCacheModel.scopeOrgId = getScopeOrgId();

		catEntryCacheModel.name = getName();

		String name = catEntryCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			catEntryCacheModel.name = null;
		}

		catEntryCacheModel.tag = getTag();

		String tag = catEntryCacheModel.tag;

		if ((tag != null) && (tag.length() == 0)) {
			catEntryCacheModel.tag = null;
		}

		catEntryCacheModel.status = getStatus();

		String status = catEntryCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			catEntryCacheModel.status = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			catEntryCacheModel.statusDate = statusDate.getTime();
		}
		else {
			catEntryCacheModel.statusDate = Long.MIN_VALUE;
		}

		return catEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<CatEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<CatEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CatEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((CatEntry)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<CatEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<CatEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<CatEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((CatEntry)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, CatEntry>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _petId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _creatorId;
	private long _scopeOrgId;
	private String _name;
	private String _tag;
	private String _status;
	private Date _statusDate;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<CatEntry, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((CatEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("petId", _petId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("creatorId", _creatorId);
		_columnOriginalValues.put("scopeOrgId", _scopeOrgId);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("tag", _tag);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("statusDate", _statusDate);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("petId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("creatorId", 256L);

		columnBitmasks.put("scopeOrgId", 512L);

		columnBitmasks.put("name", 1024L);

		columnBitmasks.put("tag", 2048L);

		columnBitmasks.put("status", 4096L);

		columnBitmasks.put("statusDate", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private CatEntry _escapedModel;

}