/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.dogoo.poc.account.service.base;

import com.dogoo.poc.account.model.CategoryEntry;
import com.dogoo.poc.account.service.CategoryEntryLocalService;
import com.dogoo.poc.account.service.CategoryEntryLocalServiceUtil;
import com.dogoo.poc.account.service.persistence.AccountEntryPersistence;
import com.dogoo.poc.account.service.persistence.CategoryEntryPersistence;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the category entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.dogoo.poc.account.service.impl.CategoryEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.dogoo.poc.account.service.impl.CategoryEntryLocalServiceImpl
 * @generated
 */
public abstract class CategoryEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, CategoryEntryLocalService, IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>CategoryEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>CategoryEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the category entry to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CategoryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param categoryEntry the category entry
	 * @return the category entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CategoryEntry addCategoryEntry(CategoryEntry categoryEntry) {
		categoryEntry.setNew(true);

		return categoryEntryPersistence.update(categoryEntry);
	}

	/**
	 * Creates a new category entry with the primary key. Does not add the category entry to the database.
	 *
	 * @param categoryId the primary key for the new category entry
	 * @return the new category entry
	 */
	@Override
	@Transactional(enabled = false)
	public CategoryEntry createCategoryEntry(long categoryId) {
		return categoryEntryPersistence.create(categoryId);
	}

	/**
	 * Deletes the category entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CategoryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param categoryId the primary key of the category entry
	 * @return the category entry that was removed
	 * @throws PortalException if a category entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CategoryEntry deleteCategoryEntry(long categoryId)
		throws PortalException {

		return categoryEntryPersistence.remove(categoryId);
	}

	/**
	 * Deletes the category entry from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CategoryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param categoryEntry the category entry
	 * @return the category entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public CategoryEntry deleteCategoryEntry(CategoryEntry categoryEntry) {
		return categoryEntryPersistence.remove(categoryEntry);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return categoryEntryPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			CategoryEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return categoryEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.poc.account.model.impl.CategoryEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return categoryEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.poc.account.model.impl.CategoryEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return categoryEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return categoryEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return categoryEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public CategoryEntry fetchCategoryEntry(long categoryId) {
		return categoryEntryPersistence.fetchByPrimaryKey(categoryId);
	}

	/**
	 * Returns the category entry matching the UUID and group.
	 *
	 * @param uuid the category entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching category entry, or <code>null</code> if a matching category entry could not be found
	 */
	@Override
	public CategoryEntry fetchCategoryEntryByUuidAndGroupId(
		String uuid, long groupId) {

		return categoryEntryPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the category entry with the primary key.
	 *
	 * @param categoryId the primary key of the category entry
	 * @return the category entry
	 * @throws PortalException if a category entry with the primary key could not be found
	 */
	@Override
	public CategoryEntry getCategoryEntry(long categoryId)
		throws PortalException {

		return categoryEntryPersistence.findByPrimaryKey(categoryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(categoryEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CategoryEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("categoryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			categoryEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(CategoryEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("categoryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(categoryEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(CategoryEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("categoryId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<CategoryEntry>() {

				@Override
				public void performAction(CategoryEntry categoryEntry)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, categoryEntry);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(CategoryEntry.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return categoryEntryPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return categoryEntryLocalService.deleteCategoryEntry(
			(CategoryEntry)persistedModel);
	}

	@Override
	public BasePersistence<CategoryEntry> getBasePersistence() {
		return categoryEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return categoryEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the category entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the category entries
	 * @param companyId the primary key of the company
	 * @return the matching category entries, or an empty list if no matches were found
	 */
	@Override
	public List<CategoryEntry> getCategoryEntriesByUuidAndCompanyId(
		String uuid, long companyId) {

		return categoryEntryPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of category entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the category entries
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of category entries
	 * @param end the upper bound of the range of category entries (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching category entries, or an empty list if no matches were found
	 */
	@Override
	public List<CategoryEntry> getCategoryEntriesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<CategoryEntry> orderByComparator) {

		return categoryEntryPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the category entry matching the UUID and group.
	 *
	 * @param uuid the category entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching category entry
	 * @throws PortalException if a matching category entry could not be found
	 */
	@Override
	public CategoryEntry getCategoryEntryByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return categoryEntryPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the category entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.dogoo.poc.account.model.impl.CategoryEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of category entries
	 * @param end the upper bound of the range of category entries (not inclusive)
	 * @return the range of category entries
	 */
	@Override
	public List<CategoryEntry> getCategoryEntries(int start, int end) {
		return categoryEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of category entries.
	 *
	 * @return the number of category entries
	 */
	@Override
	public int getCategoryEntriesCount() {
		return categoryEntryPersistence.countAll();
	}

	/**
	 * Updates the category entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect CategoryEntryLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param categoryEntry the category entry
	 * @return the category entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public CategoryEntry updateCategoryEntry(CategoryEntry categoryEntry) {
		return categoryEntryPersistence.update(categoryEntry);
	}

	/**
	 */
	@Override
	public void addAccountEntryCategoryEntry(long accountId, long categoryId) {
		accountEntryPersistence.addCategoryEntry(accountId, categoryId);
	}

	/**
	 */
	@Override
	public void addAccountEntryCategoryEntry(
		long accountId, CategoryEntry categoryEntry) {

		accountEntryPersistence.addCategoryEntry(accountId, categoryEntry);
	}

	/**
	 */
	@Override
	public void addAccountEntryCategoryEntries(
		long accountId, long[] categoryIds) {

		accountEntryPersistence.addCategoryEntries(accountId, categoryIds);
	}

	/**
	 */
	@Override
	public void addAccountEntryCategoryEntries(
		long accountId, List<CategoryEntry> categoryEntries) {

		accountEntryPersistence.addCategoryEntries(accountId, categoryEntries);
	}

	/**
	 */
	@Override
	public void clearAccountEntryCategoryEntries(long accountId) {
		accountEntryPersistence.clearCategoryEntries(accountId);
	}

	/**
	 */
	@Override
	public void deleteAccountEntryCategoryEntry(
		long accountId, long categoryId) {

		accountEntryPersistence.removeCategoryEntry(accountId, categoryId);
	}

	/**
	 */
	@Override
	public void deleteAccountEntryCategoryEntry(
		long accountId, CategoryEntry categoryEntry) {

		accountEntryPersistence.removeCategoryEntry(accountId, categoryEntry);
	}

	/**
	 */
	@Override
	public void deleteAccountEntryCategoryEntries(
		long accountId, long[] categoryIds) {

		accountEntryPersistence.removeCategoryEntries(accountId, categoryIds);
	}

	/**
	 */
	@Override
	public void deleteAccountEntryCategoryEntries(
		long accountId, List<CategoryEntry> categoryEntries) {

		accountEntryPersistence.removeCategoryEntries(
			accountId, categoryEntries);
	}

	/**
	 * Returns the accountIds of the account entries associated with the category entry.
	 *
	 * @param categoryId the categoryId of the category entry
	 * @return long[] the accountIds of account entries associated with the category entry
	 */
	@Override
	public long[] getAccountEntryPrimaryKeys(long categoryId) {
		return categoryEntryPersistence.getAccountEntryPrimaryKeys(categoryId);
	}

	/**
	 */
	@Override
	public List<CategoryEntry> getAccountEntryCategoryEntries(long accountId) {
		return categoryEntryPersistence.getAccountEntryCategoryEntries(
			accountId);
	}

	/**
	 */
	@Override
	public List<CategoryEntry> getAccountEntryCategoryEntries(
		long accountId, int start, int end) {

		return categoryEntryPersistence.getAccountEntryCategoryEntries(
			accountId, start, end);
	}

	/**
	 */
	@Override
	public List<CategoryEntry> getAccountEntryCategoryEntries(
		long accountId, int start, int end,
		OrderByComparator<CategoryEntry> orderByComparator) {

		return categoryEntryPersistence.getAccountEntryCategoryEntries(
			accountId, start, end, orderByComparator);
	}

	/**
	 */
	@Override
	public int getAccountEntryCategoryEntriesCount(long accountId) {
		return accountEntryPersistence.getCategoryEntriesSize(accountId);
	}

	/**
	 */
	@Override
	public boolean hasAccountEntryCategoryEntry(
		long accountId, long categoryId) {

		return accountEntryPersistence.containsCategoryEntry(
			accountId, categoryId);
	}

	/**
	 */
	@Override
	public boolean hasAccountEntryCategoryEntries(long accountId) {
		return accountEntryPersistence.containsCategoryEntries(accountId);
	}

	/**
	 */
	@Override
	public void setAccountEntryCategoryEntries(
		long accountId, long[] categoryIds) {

		accountEntryPersistence.setCategoryEntries(accountId, categoryIds);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			CategoryEntryLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		categoryEntryLocalService = (CategoryEntryLocalService)aopProxy;

		_setLocalServiceUtilService(categoryEntryLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return CategoryEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return CategoryEntry.class;
	}

	protected String getModelClassName() {
		return CategoryEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = categoryEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		CategoryEntryLocalService categoryEntryLocalService) {

		try {
			Field field = CategoryEntryLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, categoryEntryLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AccountEntryPersistence accountEntryPersistence;

	protected CategoryEntryLocalService categoryEntryLocalService;

	@Reference
	protected CategoryEntryPersistence categoryEntryPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}